Feature/11/setting up routes for kid
JULIERAJ/KIDS-FIRST-Back pull request #30
Opened 2024-07-15 15:48 UTC by Skyline857

Feature/backend: set up routes for Kid[#11]

Requirements
Add routes for managing Kid, use the requirements in GitBook  [(https://victorias-organization-2.gitbook.io/kids-first-app/product-details/kids-info/adding-editing-deleting  l)

Test Steps
Set Up Postman:
Open Postman to test the API endpoints.

Testing Instructions for Postman
1. Create a New Kid Profile (POST /kid)
Endpoint: POST http://localhost:3000/kid
Headers:
Content-Type: application/json
Body:
json
{
  "name": "John",
  "childColor": "blue",
  "DOB": "01/01/2015",
  "allergies": ["Peanuts"],
  "interest": ["Soccer"],
  "fears": ["Dogs"],
  "otherNotes": "Loves to play soccer"
}
Expected Response:
Status: 201 Created
Body: The created kid profile details.

2. Update an Existing Kid Profile (PUT /kid/:id)
Endpoint: PUT http://localhost:3000/kid/:id
Replace :id with the actual ID of the kid profile you want to update.
Headers:
Content-Type: application/json
Body:
json
{
  "name": "Johnny",
  "childColor": "green",
  "DOB": "01/01/2016",
  "allergies": ["Dust"],
  "interest": ["Reading"],
  "fears": ["Heights"],
  "otherNotes": "Loves reading books"
}
Expected Response:
Status: 200 OK
Body: The updated kid profile details.

3. Get All Kid Profiles (GET /kid)
Endpoint: GET http://localhost:3000/kid
Expected Response:
Status: 200 OK
Body: An array of all kid profiles.

4. Get a Specific Kid Profile (GET /kid/:id)
Endpoint: GET http://localhost:3000/kid/:id
Replace :id with the actual ID of the kid profile you want to retrieve.
Expected Response:
Status: 200 OK
Body: The details of the specific kid profile.

5. Delete a Kid Profile (DELETE /kid/:id)
Endpoint: DELETE http://localhost:3000/kid/:id
Replace :id with the actual ID of the kid profile you want to delete.
Expected Response:
Status: 204 No Content

API Changes
New Endpoints Added:
POST /kid to create a new kid profile.
PUT /kid/:id to update an existing kid profile.
GET /kid to get all kid profiles.
GET /kid/:id to get a specific kid profile.
DELETE /kid/:id to delete a specific kid profile.

Database Changes
Schema:
Ensure the kid schema includes fields like name, childColor, DOB, allergies, interest, fears, and otherNotes.

Checklist
 Pull Request title includes the issue number and a brief description of the change.
 All changes should be tested and verified to work correctly.
 Code follows backend best practices.
 Branch names follow the conventions in the contributing file.
 Commit messages follow the naming conventions in the contributing file.
 No sensitive data or secrets are included in the codebase.

2024-07-15 17:18 UTC, ElenaCherpakova requested changes

2024-07-15 17:18 UTC, ElenaCherpakova commented on routes/kids.js
> +router.post('/kid', kidController.kid);
It should be /kids/:id to follow RESTful conventions for resources. Using the plural form (kids) is a common practice as it represents the collection of all kids, and :id refers to a specific item within that collection

2024-07-15 17:24 UTC, AnnaSolovykh commented on routes/kids.js
> +    createKid,
Where is this function used?

2024-07-15 17:24 UTC, AnnaSolovykh commented on routes/kids.js
> +router.get('/kid/:id', kidController.getKid);
Where is this function imported?

2024-07-15 18:09 UTC, Skyline857 commented on routes/kids.js
> +router.post('/kid', kidController.kid);
Thank you for such a detailed response, Lena! I appreciate it a lot!

2024-07-16 16:32 UTC, AnnaSolovykh approved these changes

2024-07-17 02:38 UTC, ElenaCherpakova approved these changes

2024-07-17 02:38 UTC, ElenaCherpakova commented on routes/kids.js
> +router.post('/kids:id', kidController.createKid);
there are still issues with routes it should be` router.post('/kids/:id', kidController.updateKid);`

2024-07-17 02:38 UTC, ElenaCherpakova commented on routes/kids.js
>  router.put('/kid/:id', kidController.updateKid);
same here

2024-07-17 14:43 UTC, merged